apiVersion: secrets.phase.dev/v1alpha1
kind: PhaseSecret
metadata:
  name: dev-instance-dns-sync-phase-secret
  namespace: dev-instance-dns-sync
  annotations:
    secrets.phase.dev/redeploy: "true"  # Automatically redeploy when secrets change
spec:
  phaseApp: "devops"  # The name of your Phase application
  phaseAppEnv: "Development"  # The Phase application environment to fetch secrets from
  phaseHost: "https://phase.aops.tools"  # URL of the Phase Console instance
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: "phase-service-token"  # Name of the service token with access to your Phase application
        secretNamespace: "dev-instance-dns-sync"  # Namespace where the service token is stored
  managedSecretReferences:
    - secretName: "dev-instance-dns-sync-secret"  # Name of the Kubernetes managed secret that Phase will sync
      secretNamespace: "dev-instance-dns-sync" 